// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppConfig = { base_url: string, api_key: string, model: string, disabled_feeds: Array<string>, 
/**
 * User CEFR level (A1–C2). Words above this are underlined when reading.
 */
cefr_level: string, 
/**
 * Known vocabulary band (1000 / 3000 / 5000 / 10000 / 20000).
 * Words with frequency rank above this are underlined.
 */
freq_band: number, 
/**
 * Whether the adaptive vocab placement test has been completed.
 */
vocab_placement_done: boolean, 
/**
 * Final continuous ability L from the last placement test.
 */
vocab_placement_l: number | null, 
/**
 * ISO timestamp of the last placement test.
 */
vocab_placement_at: string | null, 
/**
 * User dismissed the placement prompt; don't force it again.
 */
vocab_placement_skipped: boolean, 
/**
 * Reader body font preset (serif / palatino / georgia / newyork / songti / sans).
 */
reader_font: string, 
/**
 * Reader body font size in px (16 / 18 / 20 / 22 / 24).
 */
reader_font_size: number, 
/**
 * Reader body line-height (1.5 / 1.65 / 1.75 / 1.9 / 2.1).
 */
reader_line_height: number, 
/**
 * Reader measure preset (narrow / medium / wide / full).
 */
reader_line_width: string, 
/**
 * UI theme preference: system | light | dark.
 */
theme: string, 
/**
 * Auto-ingested articles older than this many days are purged on refresh.
 * 0 = keep forever. Liked articles and user imports are always kept.
 */
article_retention_days: number, 
/**
 * Show a small Chinese gloss beneath "super-hard" words while reading
 * (≥2 CEFR steps above the user's level, or frequency rank past 2× the
 * band). Off = the reader stays as clean as before; underline still works.
 */
show_hard_word_gloss: boolean, };
