// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Article } from "./Article";
import type { TranslationRow } from "./TranslationRow";

export type ArticleView = { article: Article, paragraphs: Array<string>, translations: Array<TranslationRow>, };
