// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Article = { id: string, url: string, title: string, source: string, category: string, published_at: string | null, content_text: string, fetched_at: string, 
/**
 * rss = auto-ingested; url / file = user-imported (never purged by refresh).
 */
origin: string, 
/**
 * LLM-generated Simplified Chinese blurb, at most 50 characters.
 */
summary_zh: string, 
/**
 * Set when the reader is opened. Implicit; never asked.
 */
last_opened_at: string | null, open_count: number, 
/**
 * Whitespace-delimited word count of the body, stamped at ingest/refresh.
 */
word_count: number, 
/**
 * '' = not yet assessed; 'fulltext' once the body passed the readability gate.
 */
quality: string, 
/**
 * Where the final body came from: rss | page | url | file.
 */
extraction_source: string, 
/**
 * Accumulated visible reading time in milliseconds.
 */
dwell_ms: number, read_completed: boolean, liked: boolean, };
