// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FeedValidation = { ok: boolean, title: string | null, entry_count: number, error: string | null, };
