// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FeedSource = { id: string, name: string, category: string, url: string, enabled: boolean, 
/**
 * curated = built-in seed; user = subscribed via manage UI
 */
origin: string, description: string, 
/**
 * HTTP ETag from the last successful fetch; sent back as If-None-Match.
 */
etag: string, last_fetched_at: string | null, 
/**
 * Fraction of entries in the last refresh whose RSS body was trusted
 * full-text. -1 = unknown (no data yet). Drives the per-feed trust bar.
 */
fulltext_ratio: number, 
/**
 * User-assigned display priority for the sidebar source list. Higher =
 * surfaced earlier; 0 = never ordered (new feeds default here). Drives the
 * home ranking via a source-priority bonus (see `rank::Affinity`).
 */
priority: number, };
