// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TranslationRow } from "./TranslationRow";

export type FullTranslateResult = { rows: Array<TranslationRow>, errors: Array<string>, };
