// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LearningStats = { opened_total: number, opened_today: number, opened_7d: number, top_source: string | null, top_category: string | null, vocab_created_7d: number, vocab_learning: number, };
