// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One recorded term lookup (Home/Reader selection popover), newest first.
 */
export type LookupEntry = { id: number, term: string, 
/**
 * Selection/sentence the lookup came from (may be empty).
 */
context: string, article_id: string | null, created_at: string, };
