// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A saved word or phrase with spaced-repetition state. Both library lists
 * (生词 / 短语组合) live in one table, distinguished by `kind`.
 */
export type MemoryItem = { id: string, 
/**
 * "word" | "phrase"
 */
kind: string, term: string, definition_zh: string, 
/**
 * Part of speech for words; usage label (idiom / collocation …) for phrases.
 */
word_type: string, collocations: Array<string>, context_sentence: string, article_id: string | null, status: string, interval_days: number, reps: number, consecutive_know: number, next_review_at: string, created_at: string, };
