// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArticleListItem } from "./ArticleListItem";

/**
 * One read-lock snapshot for the home list: the candidate window plus every
 * affinity input the frontend needs to score it. Ranking lives in TS
 * (`src/rank.ts`); the backend only gathers rows, so a refresh landing
 * mid-score can't rank a page against a half-updated profile.
 */
export type RankWindow = { items: Array<ArticleListItem>, source_opens: Record<string, number>, category_opens: Record<string, number>, 
/**
 * (title, weight) with liked = 2.0, read-to-end = 1.0 — the semantic
 * profile input; TS turns it into term weights.
 */
engaged_titles: Array<[string, number]>, source_priority: Record<string, number>, category_priority_max: Record<string, number>, };
