// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One day of reading activity (UTC date, `YYYY-MM-DD`).
 */
export type ReadingDay = { date: string, articles: number, minutes: number, words: number, };
