// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RefreshResult = { fetched_feeds: number, added_or_updated: number, updated: number, skipped_existing: number, skipped_short: number, skipped_non_english: number, skipped_duplicate: number, 
/**
 * One-time backfill removals of synopsis-only / truncated bodies.
 */
purged_teasers: number, 
/**
 * Retention removals (articles older than the configured window).
 */
purged_old: number, feeds_unchanged: number, titles_translated: number, errors: Array<string>, };
