// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RefreshProgress = { 
/**
 * download | translate | done
 */
phase: string, current: number, total: number, label: string, 
/**
 * 0–100 overall progress across download + translate
 */
percent: number, 
/**
 * Articles newly inserted into the library so far this refresh.
 */
articles: number, };
