// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A source's share of reading (by time).
 */
export type SourceStat = { name: string, articles: number, minutes: number, };
