// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TranslateProgress = { article_id: string, current: number, total: number, scope_key: string, translated_text: string, done: boolean, };
