// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TranslationRow = { id: number, article_id: string, scope: string, scope_key: string, source_text: string, translated_text: string, model: string, };
