import { defaultReadingPrefs } from "../readingPrefs";
import type { AppConfig as RustAppConfig } from "../../src-tauri/core/bindings/AppConfig";

export type { Article } from "../../src-tauri/core/bindings/Article";
export type { ArticleListItem } from "../../src-tauri/core/bindings/ArticleListItem";
export type { LookupEntry } from "../../src-tauri/core/bindings/LookupEntry";
export type { ArticleView } from "../../src-tauri/core/bindings/ArticleView";
export type { FeedCategory } from "../../src-tauri/core/bindings/FeedCategory";
export type { FeedDiscoverCandidate } from "../../src-tauri/core/bindings/FeedDiscoverCandidate";
export type { FeedSource } from "../../src-tauri/core/bindings/FeedSource";
export type { FeedValidation } from "../../src-tauri/core/bindings/FeedValidation";
export type { FullTranslateResult } from "../../src-tauri/core/bindings/FullTranslateResult";
export type { RefreshProgress } from "../../src-tauri/core/bindings/RefreshProgress";
export type { RefreshResult } from "../../src-tauri/core/bindings/RefreshResult";
export type { TranslateProgress } from "../../src-tauri/core/bindings/TranslateProgress";
export type { TranslationRow } from "../../src-tauri/core/bindings/TranslationRow";
export type { MemoryItem } from "../../src-tauri/core/bindings/MemoryItem";
export type { LearningStats } from "../../src-tauri/core/bindings/LearningStats";
export type { ReadingStats } from "../../src-tauri/core/bindings/ReadingStats";
export type { ReadingDay } from "../../src-tauri/core/bindings/ReadingDay";
export type { SourceStat } from "../../src-tauri/core/bindings/SourceStat";
/** Generated by ts-rs from the Rust `config::AppConfig` — single source of truth. */
export type { AppConfig } from "../../src-tauri/core/bindings/AppConfig";

/**
 * First-paint placeholder: the real config arrives from `get_config`, and the
 * generated `AppConfig` type already fails the build if a field is added or
 * removed on the Rust side. Only a changed *default value* can drift here,
 * which costs one frame of the wrong preference — not worth an extra IPC call
 * at startup to eliminate.
 */
export function defaultAppConfig(): RustAppConfig {
  return {
    base_url: "https://api.openai.com/v1",
    api_key: "",
    model: "gpt-4o-mini",
    disabled_feeds: [],
    cefr_level: "B1",
    freq_band: 3000,
    vocab_placement_done: false,
    vocab_placement_l: null,
    vocab_placement_at: null,
    vocab_placement_skipped: false,
    article_retention_days: 14,
    theme: "system",
    show_hard_word_gloss: true,
    ...defaultReadingPrefs(),
  };
}
